name: Your New Jekyll Site
markdown: redcarpet
pygments: true

# Use a separate source and build folder:
source: ./src
destination: ./build

permalink: /blog/:categories/:title

# Configuration for the asset pipeline
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - bower_components
  compress:
    css: sass
    js: uglifier